services:
    _defaults:
        public: true
        autowire: true

    OxidEsales\MonduPayment\Core\Http\MonduClient:
        public: true

    OxidEsales\MonduPayment\Services\BuyerFeeCentsServiceInterface:
        class: OxidEsales\MonduBuyerFeeCents\BuyerFeeCents
        public: true